[build]
command = "npx next build --webpack"
publish = ".next"

[functions]
directory = ".netlify/functions"

[context.production.environment]
NEXT_PUBLIC_ANALYTICS_BRANCH_ID = "/dji-marketing"

[[plugins]]
package = "@netlify/plugin-nextjs"
